[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0"
async-trait = "0.1"

[build-dependencies]
tonic-build = "0.8"